apiVersion: v1
kind: Service
metadata:
  name: websockets
  labels:
    app: websockets
spec:
  ports:
  - port: 3000
    name: http
  selector:
    app: websockets
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: websockets
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: websockets
        version: v1
    spec:
      containers:
      - image: gcr.io/nandanks-151422/websockets
        imagePullPolicy: IfNotPresent
        name: websockets
        ports:
        - containerPort: 3000
        resources:
          requests:
            cpu: 100m
      nodeSelector:
        cloud.google.com/gke-nodepool: apps                             
