apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: websockets-port
  namespace: apps
spec:
  host: websockets.apps.svc.cluster.local
  trafficPolicy: 
    portLevelSettings:
    - port:
        number: 3000
      loadBalancer:
        simple: ROUND_ROBIN