apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: websockets
  namespace: apps
spec:
  hosts:
  - websockets
  http:
  - timeout: 5s  
    rewrite:
      authority: websockets.apps.svc.cluster.local   
    route:
    - destination:
        host: websockets.apps.svc.cluster.local